---
name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ruby/setup-ruby@v1.144.0
        with:
          bundler-cache: true
      - run: bundle exec rubocop --fail-level=autocorrect
