---
name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: ruby/setup-ruby@v1.174.0
        with:
          bundler-cache: true
      - run: bundle exec rubocop --fail-level=autocorrect
